from django.test import TestCase
from rest_framework.test import APIClient


class ProjectCreationTestCase(TestCase):
    def setUp(self): ...

    def test_successful_project_creation(self): ...

    def test_project_creation_with_empty_title(self): ...

    def test_project_creation_with_too_long_title(self): ...

    def test_project_creation_with_too_long_description(self): ...

    def test_project_creation_without_authentication(self): ...
