name: Issue Related Tests

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  issue-related-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'

    - name: Install pipenv and generate requirements.txt
      run: |
        pip install pipenv
        pipenv lock -r > requirements.txt
        cat requirements.txt

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Set PYTHONPATH and check environment
      run: |
        echo "Current working directory: $(pwd)"
        ls -la
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        echo "PYTHONPATH: $PYTHONPATH"
        which python
        python --version

    - name: Run API script
      run: |
        python core/utils/issue_related_tests.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO: ${{ github.repository }}
        OWNER: ${{ github.repository_owner }}
        BRANCH: ${{ github.head_ref }}
        DJANGO_SETTINGS_MODULE: 'REsQue.settings'
        PYTHONUNBUFFERED: "1"

    - name: Check for script errors
      if: failure()
      run: |
        echo "The script failed to run. Please check the logs for more information."
        cat core/utils/issue_related_tests.py
        exit 1